name: sx128x-util
base: core18 # the base snap is the execution environment for this snap
version: git

summary: Semtec SX128x Radio IC utility
description: |
  A utility for testing and interacting with Semtech SX128x series
  2.4 GHz Radio ICs

architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf

grade: devel
confinement: strict

apps:
  sx128x-util:
    command: bin/sx128x-util
    plugs:
    - gpio
    - spi

parts:
  util:
    source: .
    plugin: rust

